=== ghilasmzn/MailStone/communication/DTD/response/response.dtd
<!ELEMENT issues (issue)>
<!ATTLIST issues code CDATA #REQUIRED>
<!ELEMENT issue (product|description|resolved|solution)>
<!ELEMENT product (ref|date|name|brand|category|client)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT category (name)>
<!ELEMENT client (firstname|lastname|email|address|phoneNumber)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT resolved (#PCDATA)>
<!ELEMENT solution (description|cost|duration)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT duration (#PCDATA)>

=== ghilasmzn/MailStone/communication/archived/response/response0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE issues SYSTEM "C:\Users\Administrateur\Desktop\PROJECT MAILSTONE\2app\communication\DTD\response\response.dtd">
<issues code="r001">
    <issue>
        <product>
            <ref>000</ref>
            <date>22-11-2022</date>
            <name>reference</name>
            <brand>toshiba</brand>
            <category>
                <name/>
            </category>
            <client>
                <firstname>Idriss</firstname>
                <lastname>Benguezzou</lastname>
                <email>idrissbenguezzou@gmail.com</email>
                <address/>
                <phoneNumber/>
            </client>
        </product>
        <description>Mon pc affiche un Ã©cran noir  il ne s allume plus   </description>
        <resolved>false</resolved>
        <solution>
            <description/>
            <cost/>
            <duration/>
        </solution>
    </issue>
</issues>
